blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from . import views
from .views import (

    HomeView,
    PostDetailView,
    like

)
app_name = 'blog'

urlpatterns = [

    path('', HomeView.as_view(), name='home'),
    path('<slug>/', PostDetailView.as_view(), name='detail'),
    path('like/<slug>/', views.like, name='like')
]

news/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.shortcuts import reverse

# Create your models here.


class User(AbstractUser):
    pass

    def __str__(self):
        return self.username


class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    image = models.ImageField(upload_to='photos/')
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=15)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        unique_together = ['title', "slug"]

    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"slug": self.slug})

    def get_like_url(self):
        return reverse("blog:like", kwargs={"slug": self.slug})

    @property
    def get_comment_count(self):
        return self.comment_set.all().count()

    @property
    def comment(self):
        return self.comment_set.all()

    @property
    def get_view_count(self):
        return self.postview_set.all().count()

    @property
    def get_like_count(self):
        return self.like_set.all().count()


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class PostView(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Like(models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

news/forms.py
from django import forms


class CommentForm(forms.Form):
    comment = forms.CharField(required=True, widget=forms.Textarea(attrs={

        'class': 'form-control',
        'row': 6,
        'resize': 'none',
        'label': 'Comment'

    }))

news/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView
from .models import Post, Like, PostView, Comment
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import CommentForm
# Create your views here.


class HomeView(ListView):

    model = Post
    paginate_by = 10
    template_name = 'index.html'


class PostDetailView(DetailView):
    model = Post
    template_name = 'detail.html'

    def post(self, *args, **kwargs):
        form = CommentForm(self.request.POST)
        if form.is_valid():
            post = self.get_object()
            form.user = self.request.user
            form.comment = form.cleaned_data.get('comment')
            form.post = post

            comment = Comment(
                user=form.user,
                content=form.comment,
                post=form.post
            )
            comment.save()
            return redirect('blog:detail', slug=post.slug)
        return redirect('blog:detail', slug=self.get_object().slug)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'form': CommentForm()
        })
        return context

    def get_object(self, **kwargs):
        object = super().get_object(**kwargs)
        if self.request.user.is_authenticated:
            PostView.objects.get_or_create(user=self.request.user, post=object)
        return object


@login_required
def like(request, slug):
    post = get_object_or_404(Post, slug=slug)
    like_qs = Like.objects.filter(user=request.user, post=post)
    if like_qs.exists():
        like_qs[0].delete()
        messages.error(request, "Oh no!! You just unliked the post")
        return redirect('blog:detail', slug=slug)
    Like.objects.create(user=request.user, post=post)
    messages.success(request, "Yay!! You just liked the post")
    return redirect('blog:detail', slug=slug)

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="../assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
 
    {% block header %}
    
    {% endblock header %}
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />

    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">

    <!-- CSS Files -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
     <link href="{% static 'css/mdb.lite.min.css' %}" rel="stylesheet" />
          <link href="{% static 'css/material-kit.min.css' %}" rel="stylesheet" />
                    <link href="{% static 'css/material-kit.min.css' %}" rel="stylesheet" />
      <link href="{% static 'css/style.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/now-ui-kit.css?v=1.2.0' %}" rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'css/now-ui-kit.css' %}">
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link href="{% static 'demo/demo.css' %}" rel="stylesheet" />
  </head>
  <body>
    <!-- Navbar Primary  -->
            <nav class="navbar navbar-expand-lg bg-primary">
              <div class="container">
                <div class="navbar-translate">
                  <a class="navbar-brand" href="{% url 'blog:home' %}">Home</a>
                  <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#example-navbar-primary" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-bar bar1"></span>
                    <span class="navbar-toggler-bar bar2"></span>
                    <span class="navbar-toggler-bar bar3"></span>
                  </button>
                </div>
                <div class="collapse navbar-collapse" id="example-navbar-primary">
                  <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                      <a class="nav-link" href="#pablo">
                       
                      
                      </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#pablo">
              
                  
                      </a>
                    </li>
                   {% if request.user.is_authenticated %}
                   
                    <li class="nav-item">
                      <a class="nav-link" href="#">
                      <i class="now-ui-icons users_single-02"></i>
                        <p>hi {{user.username }}</p>
                      </a>
                    </li>
                     <li class="nav-item">
                      <a class="nav-link" href="{%  url 'account_logout'%}">
              
                  Logout
                      </a>
                    </li>
                    {%else %}
                     <li class="nav-item">
                      <a class="nav-link" href="{% url 'account_login' %}">
                      <i class="now-ui-icons users_single-02"></i>
                        <p>Login</p>
                      </a>
                    </li>
                      <li class="nav-item">
                      <a class="nav-link" href="{% url 'account_signup' %}">
                   <i class="now-ui-icons users_circle-08"></i>
                        <p>Signup</p>
                      </a>
                    </li>
                    {% endif %}
                  </ul>
                </div>
              </div>
            </nav>
            <!-- End Navbar Primary -->

{% if messages %}
 {% for message in messages %}
 <div class="alert alert-{{ message.tags }}" role="alert">
  <div class="container">
    <div class="alert-icon">
      <i class="now-ui-icons ui-2_like"></i>
    </div>
    <strong>{{ message }}</strong> 
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">
        <i class="now-ui-icons ui-1_simple-remove"></i>
      </span>
    </button>
  </div>

</div>
  {% endfor %}

{% endif %}
  {% block content %}
  {% endblock content %}

    <!--   Core JS Files   -->
    <script src="{% static 'js/core/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>

    <!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
    <script src="{% static 'js/plugins/bootstrap-switch.js' %}"></script>

    <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
    <script src="{% static 'js/plugins/nouislider.min.js' %}" type="text/javascript"></script>

    <!--  Plugin for the DatePicker, full documentation here: https://github.com/uxsolutions/bootstrap-datepicker --><script src="{% static 'js/plugins/bootstrap-datepicker.js' %}" type="text/javascript"></script>

    <!--  Google Maps Plugin    -->
    <script  src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>


    <!-- Control Center for Now Ui Kit: parallax effects, scripts for the example pages etc -->
    <script src="{% static 'js/now-ui-kit.js' %}" type="text/javascript"></script>
  </body>
</html>

templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}
{% block header %}
<title>{{object.title}}</title>
{% endblock %}
{% block content %}


<div class="page-header page-header-small">
    <div class="page-header-image" style="background-image: url({{object.image.url}});">
    </div>
    <div class="content-center">
        <div class="container">
            <h1 class="title">{{object.title}}</h1>
            <h4> Posted {{object.publish_date|timesince}} ago</h4>
            <h4>Post By {{object.author|upper}} </h4>

        </div>
    </div>
</div>
<div class="section">
    <div class="container ">
        <div class="row">



            <div class="col-8 mx-auto ">
                <div class="card">
                    <img class="card-img-top" src="{{object.image.url}}" alt="Card image cap">
                    <div class="card-body">
                        <h4 class="card-title">{{object.title}}</h4>
                        <hr />

                        <div class="pt-1">
                            <p class="card-text">
                                <span>{{object.publish_date|timesince}}</span>
                                <span><i class="ml-2 fas fa-eye"></i> {{object.get_view_count }}</span>
                                <span><i class=" ml-2 now-ui-icons ui-2_like"> {{object.get_like_count }}</i> </span>
                                <span><i class=" ml-2 now-ui-icons ui-2_chat-round">
                                        {{object.get_comment_count }}</i></span>
                            </p>
                        </div>

                        <hr />
                        <div class="pt-1">
                            <p class="card-text">{{object.content}}</p>

                        </div>
                        <h4>Enjoyed the post?
                            Leave a like</h4> <br>
                        <a href="{{object.get_like_url}}"><i class="pt-2 pb-2 now-ui-icons ui-2_like">
                                {{object.get_like_count }}</i> </a>


                        <div class="pt-2">
                            Leave A Comment


                        </div>

                        <hr />
                        {% if request.user.is_authenticated %}
                        <div>
                            <form method="POST">
                                {% csrf_token %}
                                {{form|crispy}}

                                <button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                        </div>


                          

                            {% else %}

                            <a href="{% url 'account_login' %}" class="btn btn-primary btn-block">Login To Comment </a>
                            {% endif %}
                                            <div>
                                          
                                

                            {% for comment in object.comment %}

                            <h5> {{ comment.content }}</h5>
                            <small> By {{ comment.user|upper }}</small> <br>
                            <small>{{ comment.time|timesince }} ago</small>
   {% endfor %}
  </div> 

                      
                    </div>
                    
        
                </div>
            </div>


        </div>

    </div>
</div>



{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}


<div class="page-header page-header-small">
    <div class="page-header-image" style="background-image: url({% static 'img/bg2.jpg' %});">
    </div>
    <div class="content-center">
        <div class="container">
            <h1 class="title">Hello There</h1>
            <h4>Welcome To My Blog.</h4>

        </div>
    </div>
</div>
<div class="section">
    <div class="container ">
        <div class="row">
            {% for object in object_list  %}


            <div class="col-4"> <a href="{{object.get_absolute_url }}">
                    <div class="card">
                        <img class="card-img-top" src="{{object.image.url}}" alt="Card image cap">
                        <div class="card-body">
                            <h4 class="card-title">{{object.title}}</h4>
                            <p class="card-text">{{object.content|truncatechars:10}}</p>

                            <p class="card-text">
                                <span>{{object.publish_date|timesince}}</span>
                                <span><i class="ml-2 fas fa-eye"></i> {{object.get_view_count }}</span>
                                <span><i class=" ml-2 now-ui-icons ui-2_like"> {{object.get_like_count }}</i> </span>
                                <span><i class=" ml-2 now-ui-icons ui-2_chat-round">
                                        {{object.get_comment_count }}</i></span>
                            </p>
                        </div>
                    </div>
                </a>
            </div>

            {% endfor %}

        </div>
        <div class="separator separator-primary"></div>
        <div class="content-center">
            <div class="container">
            {% if is_paginated %}
              <nav aria-label="...">
  <ul class="pagination pagination-primary">
  {% if page_obj.has_previous %}
    <li class="page-item">
  <a class="page-link" href="?page={{page_obj.previous_page_number}}">Previous</a>
    </li>
    {% endif %}
 
    <li class="page-item active">
      <span class="page-link">
       {{page_obj.number}}
        <span class="sr-only">(current)</span>
      </span>
    </li>

    {% if page_obj.has_next %}  <li class="page-item">
      <a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a>
    </li>
    {% endif %}  
  </ul>
</nav>
{% endif %}
            </div>
        </div>
    </div>
</div>



{% endblock %}